services:
  cdplayer-backend:
    image: docker.dingo.bar/cdapi:latest
    devices:
      - "/dev/cdrom:/dev/cdrom:rwm"
    volumes:
      - "/dev/cdrom:/dev/cdrom"
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - cdplayer-network

  cdplayer-frontend:
    image: nginx:alpine
    ports:
      - "4080:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/style.css:/usr/share/nginx/html/style.css
      - ./frontend/cdfunctions.js:/usr/share/nginx/html/cdfunctions.js
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cdplayer-backend
    networks:
      - cdplayer-network

networks:
  cdplayer-network:
    driver: bridge
